#!/usr/bin/env bash

#symlink using gnu stow

gitdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#edit files for osx
#edit .zshrc
sed -e '/# virtualenvs/{N;N;d;}' -e 's/\[kcu/\[cu/g' $gitdir/shell/.zshrc > $gitdir/osx/.zshrc

if [ "$(uname)" = "Linux" ]; then
    stow -v${@/-/} -d "$gitdir" -t "$HOME" -S ncmpcpp nvim bin shell tmux git lftp

elif [ "$(uname)" = "Darwin" ]; then
    #stow the packages
    stow -v${@/-/} -d "$gitdir" -t "$HOME" -S nvim osx git lftp tmux
    stow --ignore="^((?!.config).)*$" -v${@/-/} -d "$gitdir" -t "$HOME" -S shell
fi

