#!/usr/bin/env bash
#open ncmpcpp and visualizer in tmux session

#start gmusicproxy if not running
if [[ -z "$(pgrep GMusicProxy)" ]]; then
    $HOME/.virtualenvs/gmusicproxy/bin/GMusicProxy &
fi

#start tmux session if not already running
if [[ -z "$(tmux ls | grep Music)" ]]; then
    tmux new-session -d -s Music "ncmpcpp"
    tmux split-window -d -t Music -l 12 "ncmpcpp -c .config/ncmpcpp/visualizer"
    #get rid of the status bar and borders
    tmux set -g status off
    tmux set -g pane-border-fg black
fi

#open urxvt and attach if not already open
if [[ -z "$(wmctrl -l | grep Music)" ]]; then
    urxvt -g 100x40 -T Music -e zsh -c "tmux attach-session -t Music" &
fi


