#!/usr/bin/env bash
#open ncmpcpp and visualizer in tmux session

#start gmusicproxy if not running
if [[ -z "$(pgrep GMusicProxy)" ]]; then
    $HOME/.virtualenvs/gmusicproxy/bin/GMusicProxy >/dev/null 2>&1 &
fi

#start tmux session if not already running
if [[ -z "$(tmux ls 2>/dev/null | grep -o Music)" ]]; then
    tmux new-session -d -s Music 'ncmpcpp'
    tmux split-window -d -t Music -l 10 "ncmpcpp -c $HOME/.config/ncmpcpp/visualizer"
fi

#open urxvt and attach if not already open
if [[ -z "$(wmctrl -l | grep -o Music)" ]]; then
    urxvt -g 100x40 -T Music -e zsh -c "tmux attach-session -t Music" &
fi

