#!/usr/bin/env bash
#open ncmpcpp and ncmpcpp visualizer in dedicated workspace
#assumes that i3 config contains:
#for_window [instance="floating"] floating enable

#start gmusicproxy if not running
if [[ -z "$(pgrep GMusicProxy)" ]]; then
    $HOME/.virtualenvs/gmusicproxy/bin/GMusicProxy &
fi

#check if already open
if [[ -z "$(xwininfo -tree -root | grep floating-music)" ]]; then
    exec urxvt -g 120x28 -name floating-music1 -e "ncmpcpp" &
    exec urxvt -g 120x17 -name floating-music2 -e ncmpcpp --config $HOME/.config/ncmpcpp/visualizer  &
    sleep 0.1s
    i3-msg -q '[instance="floating-music1"] move container to workspace "♬" border none move up 190px'
    i3-msg -q '[instance="floating-music2"] move container to workspace "♬" border none move down 218px'
fi

i3-msg -q 'workspace "♬", focus'

