#! /usr/bin/env bash
#script to generate configs with changable variables

#to create templates, copy your config file, and
#prepend all existing '$' with a backslash '\'
#and then edit any values you want to be replace with variables
#only tested with xresources, i3 config, and vim theme

#import fonts
#font, size
# fonts
. $HOME/scripts/templates/fonts

#import colors
#gruvbox
. $HOME/scripts/templates/colors

#.Xresources
xresources_template="$HOME/scripts/templates/Xresources.tl"

eval "cat << EOF 
$(cat ${xresources_template})
EOF" > "$HOME/.Xresources"

xrdb $HOME/.Xresources

#i3 config
i3_template="$HOME/scripts/templates/i3.tl"

eval "cat << EOF 
$(cat ${i3_template})
EOF" > "$HOME/.config/i3/config"

i3 restart &> /dev/null

#vim config
vim_template="$HOME/scripts/templates/vim.tl"

eval "cat << EOF 
$(cat ${vim_template})
EOF" > "$HOME/.config/nvim/colors/gruvbox.vim"

