#!/usr/bin/env bash

display=$(mpc current)
vol='   '

case $BLOCK_BUTTON in
    1) mpc -q prev ;;
    2) mpc -q toggle ;;
    3) mpc -q next ;;
    4) mpc -q volume -5; vol=$(mpc | grep "^vol" | grep -o "[0-9]*%\+") ;;
    5) mpc -q volume +5; vol=$(mpc | grep "^vol" | grep -o "[0-9]*%\+") ;;
esac

echo "$display  $vol"
echo "$display  $vol"
echo "#83a598"
