#!/usr/bin/env bash

#check for updates
list=($(checkupdates))
size=${#list[@]}
#if updates are available, list the number of packages, otherwise show just icon
if [ "$size" != "0" ]; then
        echo "$size"
        echo "$size"
        echo "#d3869b"
        click="urxvt -g 70x20 -name floating -e yaourt -Syua"
else
        echo " "
        echo " "
        echo "#b16286"
fi

#left click to update pacman, right click to update aur packages
case $BLOCK_BUTTON in
        1|3) $click ;;
esac
