#reload config
bind r source-file ~/.config/tmux/tmux.conf

set -g history-limit 50000
set -g set-clipboard on

# kill on close
set -g destroy-unattached on

# controls
set -g mouse on
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

is_editor='#{m/ri:^(vim?|vimdiff|nvim|hx)$,#{pane_current_command}}'
bind -n C-w if "#{?$is_editor,false,true}" { kill-pane } { send-keys "C-w" }
bind -n C-t new-window

# theme
set -g cursor-style "bar"
set -g set-titles on
set -g set-titles-string "#T"

set -g status-position top
set -g status-justify centre
set -g window-status-separator ' • '
set -g status-style 'fg=black'
set -g status-left-length 30
set -g status-left-style '#{?client_prefix,bg=yellow,bg=#94e2d5}'
set -g status-left ' #{user}@#H '
set -g status-right '#{s/./ /i:#{E:status-left}}'

set -g window-status-current-format ' #I #T '
set -g window-status-current-style 'fg=white'
set -g window-status-format ' #I #T '
set -g window-status-style 'fg=grey39'

set -g pane-border-style 'fg=grey23 bg=default'
set -g pane-active-border-style 'fg=grey23 bg=default'
