name: main_stack
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    networks: [pub]
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /mnt/3/mus/:/music
      - /mnt/1/dl/:/downloads
      - /docker/beets:/config
    restart: unless-stopped

  calibre:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web
    networks: [pub]
    ports:
      - 50005:8083/tcp
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /docker/calibre-web:/config
      - /mnt/3/book:/calibre-library
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    networks: [pub]
    command: ["tunnel", "run"]
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped

  docky:
    image: git.spaceman.one/spaceman/docky:latest
    container_name: docky
    networks: [pub]
    ports:
      - 8090:80
    environment:
      - USERNAME=${DOCKY_USERNAME}
      - PASSWORD=${DOCKY_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  git:
    image: codeberg.org/forgejo/forgejo:15-rootless
    container_name: git
    user: 1000:100
    networks: [pub]
    ports:
      - 3999:3000
      - 2222:2222
    environment:
      - USER_UID=1000
      - USER_GID=100
      - FORGEJO__server__LANDING_PAGE=/explore/repos
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service__SHOW_MILESTONES_DASHBOARD_PAGE=false
      - FORGEJO__service.explore__DISABLE_USERS_PAGEtrue
      - FORGEJO__service.explore__DISABLE_ORGANIZATIONS_PAGE=true
      - FORGEJO__repository__DEFAULT_REPO_UNITS=repo.code,repo.releases
      - FORGEJO__repository__DEFAULT_MIRROR_UNITS=repo.code,repo.releases
      - FORGEJO__repository__ENABLE_PUSH_CREATE_USER=true
      - FORGEJO__ui__SHOW_USER_EMAIL=false
    volumes:
      - /docker/forgejo:/var/lib/gitea
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks: [pub]
    ports:
      - 50500:8096 # http
      - 50501:8920 # https
      - 7359:7359/udp
      - 1900:1900/udp
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=http://10.0.0.4:50500
    volumes:
      - /docker/jellyfin:/config
      - /mnt/1/mov/tv/:/data/tvshows
      - /mnt/1/mov/movies/:/data/movies
    restart: unless-stopped

  koito:
    image: gabehf/koito:latest
    container_name: koito
    networks: [pub]
    ports:
      - 4110:4110
    volumes:
      - /docker/koito:/etc/koito
    restart: unless-stopped
  multi-scrobbler:
    image: ghcr.io/foxxmd/multi-scrobbler:latest
    container_name: multi-scrobbler
    networks:
      - pub
    ports:
      - 9078:9078
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=100
    restart: unless-stopped

  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    depends_on: [miniflux-db]
    networks: [pub, priv]
    ports:
      - 51111:8080/tcp
    environment:
      - DATABASE_URL=${MINIFLUX_DATABASE_URL}
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${MINIFLUX_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${MINIFLUX_ADMIN_PASSWORD}
    restart: unless-stopped
  miniflux-db:
    image: postgres:18
    container_name: miniflux-db
    networks: [priv]
    environment:
      - POSTGRES_DB=miniflux
      - POSTGRES_USER=${MINIFLUX_POSTGRES_USER}
      - POSTGRES_PASSWORD=${MINIFLUX_POSTGRES_PASSWORD}
    volumes:
      - /docker/miniflux:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    networks: [pub]
    ports:
      - 55666:4533/tcp
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /docker/navidrome:/data
      - /mnt/3/mus:/music
    restart: unless-stopped

  rt:
    image: ghcr.io/crazy-max/rtorrent-rutorrent:latest
    container_name: rt
    networks: [pub]
    ports:
      - 6881:6881/udp # RT DHT
      - 55000:50000/tcp # RT Incoming
      - 50001:8080/tcp # RUT Webui
      - 8000:8000/tcp # XMLRPC
      - 9000:9000/tcp # WEBDAV
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /docker/rtorrent:/data
      - /docker/rtorrent/passwd:/passwd
      - /mnt/1/dl/downloads:/downloads
      - /mnt/1/dl/watch:/data/rtorrent/watch
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    networks: [pub, priv]
    ports:
      - 45000:8080
    environment:
      - SEARXNG_VALKEY_URL=valkey://searxng-cache:6379/0
    volumes:
      - /docker/searxng:/etc/searxng
      - /docker/searxng/cache:/var/cache/searxng
    restart: unless-stopped
  searxng-cache:
    image: valkey/valkey:9-alpine
    container_name: searxng-cache
    networks: [priv]
    command: ["valkey-server", "--save", "30", "1", "--loglevel", "warning"]
    volumes:
      - valkey-data:/data
    restart: unless-stopped

  silverbullet:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    container_name: silverbullet
    networks: [pub]
    ports:
      - 3000:3000/tcp
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - SB_REMEMBER_ME_HOURS=720
      - SB_USER=${SB_USER}
    volumes:
      - /home/spaceman/notes:/space

networks:
  pub:
    name: pub
    driver: bridge
    enable_ipv6: true
  priv:
    driver: bridge
    name: priv
    internal: true
volumes:
  valkey-data:
    name: valkey-data
